print("Muhammad Marsanda Zarkasih")
print("I0322085")
print("Tegal")
print("Rumahku di dekat jalan tol dan dekat kantor desa mempunyai taman yang luas dan di sebelah rumah ada")
print("Bisa membuat pabrik dan menerapkan ilmunya")